### ISSUE TITLE
https 로 바꾸기

### ISSUE THREAD

**Issue by wafe** [ModernPUG/php-the-right-way#126]
- 영어 공식 사이트는 https 로 서비스 되고 있음 (http://phptherightway.com/ 로 가도 https 로 리다이렉트됨)
- 한국어판이 포함하고 있는 리소스 URI 나 링크들 중 http 로 고정되어 있는 것들을 손보아야 함
- 영어 공식 사이트에서 한국어판 링크를 누르면 http 로 링크가 걸려있어서 수정 요청해야 함.

**Comment by tael-mesh** [comment]
@smartbos 링크를 참고해서 조치할수있을것 같은데요?
https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https

**Comment by wafe** [comment]
설정을 조치할 수 있는 방법도 있군요!
일단 저한테는 저장소 설정 메뉴는 노출이 되지 않는군요 ㅠ.ㅠ

**Comment by smartbos** [comment]
완료했습니다~
