### ISSUE TITLE
전문용어 표기에 관해서.

### ISSUE THREAD

**Issue by wan2land** [ModernPUG/php-the-right-way#17]
문서 번역에서 용어를 통일해서 사용하는건 참 중요합니다. 이번에 정리를 하다보니 "Test Driven Development"와 같은 용어의 경우 "테스트 주도 개발"이라고 처음에 했다가 이후에 제목 정리할때 "테스트 주도 개발 (TDD)"라고 했습니다. 개발자 분들 TDD라는 말이 더 익숙할 것 같아서 그렇게 했습니다. 이처럼 전문용어의 경우 한글 번역과 전문 용어를 함께 표기하는 방향으로 가면 어떨런지요? :smile: 

그 외의 예시
- 에러 (Errors)
- 예외 (Exceptions)

정도 생각나는데 또 어떤것들이 있을까요.. : )

**Comment by smartbos** [comment]
이해에 도움이 되는 경우에는 영문을 함께 표기하는 게 좋은 것 같습니다.

**Comment by tael** [comment]
포스팅에 2가지 주제가 있군요.

### 한글번역표기에 대해

예를 들어 주신 `예외, 에러, 테스트 주도 개발` 의 경우는 모두 한글 표기만 하였으면 합니다.
애매하거나, 논란이 있는 번역표현의 경우에만 `예외(Exception)` 와 같은 표현을 사용하는 것이 매끄러울 것 같습니다.

### 번역 용어의 통일성

여러 사람이 만드는 컨텐츠의 통일성을 유지하는 것이 중요하다는 것에 동의합니다.

#### 1인관리

작은 규모의 경우 한명이 일관적으로 검수하는 것도 방법이지만 개인적으로 선호하는 방식은 아닙니다.

#### 공통사전

딕셔너리 파일을 관리하여 공유하는 것도 좋습니다.
예) 번역용어.txt
- Test Driven Development => 테스트 주도 개발
- Errors => 에러
- Exceptions => 예외

#### 이슈트래커

먼저, 적당한 형태로 번역하고, 이슈를 통해 전체의 의견을 구해보는 방식도 있습니다.
Exception을 예외가 아니라 에러라고 이해하고 번역할수도 있습니다.
애매하게 느끼지만 에러라는 표현이 좋을 것 같다면 에러라고 번역후에, 이슈트래커에 내용을 올려서 같이 검토하고,
에러가 아니라 예외가 맞다고 판정되면 그 후에 번역을 수정합니다.

### 결론

저는 3번째 이슈트래커 방식이 가장 편하다고 생각합니다.
그룹 번역의 경우 어체나 용어가 문제되고 오역에 대해서도 문제가 많습니다만,
많은 사람들이 참여하고 쉽게 시도하려면 규칙은 적을 수록 좋습니다.
고퀄리티를 강요받는게 당연한 상업성 번역과의 차이점이라고 생각합니다.

만약 규칙을 정해야 한다면, 진행이 되는 과정에 겪는 고통을 먼저 경험해 보는 것도 좋겠다는 생각입니다.

**Comment by smartbos** [comment]
많은 사람이 참여하려면 규칙이 적을수록 좋다는 말이 끌리네요 ㅎㅎ

**Comment by wan2land** [comment]
네 저도 3번 의견에 동의합니다. : )

**Comment by wafe** [comment]
제안해 주신대로 주요 단어별로 대역표가 있어서 모두 참조할 만한 가이드가 있으면 좋을 것 같습니다. 가이드에는 단순히 영단어=>번역단어 매칭 뿐 아니라 맥락에 따른 설명도 곁들일 수 있으면 좋겠죠.

예시로 들어주신 에러, 예외 의 경우에는 제가 번역할 때에도 예시해 주신 것과 동일한 규칙으로 번역해 둔 사례가 있습니다. 참조 : http://modernpug.github.io/php-the-right-way/#errors_and_exceptions

그 외에 생각나는 용어 번역의 예시가 몇 가지 있어서 나열해봅니다.
- Functional Programming => 함수형 프로그래밍
- Object-oriented Programming => 개체지향 프로그래밍 
- Object => 개체.
- instance => 인스턴스 ex) 클래스 인스턴스, 개체 인스턴스

**Comment by wan2land** [comment]
install, setup의 경우 둘다 설치하기인데 분리해서 번역해야할까요?

**Comment by tael** [comment]
이 쓰레드에서는 가이드하는 방법이나 방침에 대해 이야기 하고,
구체적인 사례는 별도로 논의하는 것이 좋을 것 같습니다.

주제와 관련하여 한가지 '권장사항' 정도로 정하고 싶은 것은, 
맥락에 따른 번역이 중요하기 때문에 이와 관련된 질문은 '링크' 를 통해 원문을 볼 수 있으면 좋을것같습니다.
물론 복사/붙여넣기를 통해서 해도 되지만 큰 맥락을 보기 위해서는 전체 구문이 나을 것 같네요.
(...근데 마크다운으로 내부링크를 어떻게 걸죠?...)

번역 단어의 가이드와 관련된 '딕셔너리'? 파일을 생성하는 것에 대한 의견을 얻고자 합니다.
아마도 내부는 이런 내용이 될 것입니다. (마크다운을 잘 쓸줄몰라서 포맷이 별로인데 일단 내용만..)
원문 단어 => 번역 단어
원문 예제 => 번역 예제 (1개정도만 있으면 됩니다)

```
---------
# Functional Programming => 함수형 프로그래밍

ex) php is not only functional programming language but also object-oriented programming language.

=> php는 함수형 프로그래밍 언어 임과 동시에 개체지향 프로그래밍 언어입니다.



# Object-oriented Programming => 개체지향 프로그래밍

ex) php is not only functional programming language but also object-oriented programming language.

=> php는 함수형 프로그래밍 언어 임과 동시에 개체지향 프로그래밍 언어입니다.

----------
```

그리고 저는, 개인적인 입장에서 이런 문서를 남기는 것을 좋아하지는 않습니다.
그래서 반대합니다. :D

**Comment by tael** [comment]
이 이슈 @wan2land  님이 정리해서 결론 내리고 close 해주시면 좋겠습니다.

**Comment by wan2land** [comment]
법칙이 많으면 여러사람이 참여하기 힘들다는 의견에 200% 동의하기 때문에, 전체적인 문장으로 봤을 때 어색하지만 않으면 무조건 OK.
그리고 누군가 어색하다 느끼거나, 더 나은 단어가 나오면 풀리퀘스트나 이슈를 통해 정리하는 걸로 합시다. : -)
