### ISSUE TITLE
/CONTRIBUTING.md

### ISSUE THREAD

**Issue by wan2land** [ModernPUG/php-the-right-way#7]
1. Use language agnostic urls when refering to external websites such as the [php.net](http://php.net/urlhowto.php) manual

번역

**Comment by tael** [comment]
참고링크;;;

http://en.wikipedia.org/wiki/Language-agnostic

**Comment by tael** [comment]
일단 의미는 ;;;

사용국가의 언어를 알 수 없는 URL(-언어 범용적인 URL을 의미, language agnostic urls)을 사용하세요. php.net 매뉴얼 과 같은 외부 링크를 참조할 경우에는 ...

# 정리하자면 ...

##### 외부 웹사이트를 참조하는 경우에는 php.net 매뉴얼(링크!) 에서 하는 것 처럼 범용 언어를 대응하는 URL을 사용하세요.

정도 될듯 하네요.

#### 참고

 php link에 ... http://php.net/urlhowto.php 어떤식으로 URL을 사용해야 하는지 나와있습니다.

예)
language agnostic url : http://php.net/join (권장)
english url : http://php.net/manual/en/function.join.php (비권장)
korean url : http://php.net/manual/kr/function.join.php (비권장)

**Comment by wan2land** [comment]
초월번역 리플을 지금 보았습니다. 
Git Issue는 일종의 여러 사람이 동시에 달려들기 방지용 Lock정도로 활용하면 되고 ModernPUG에 직접 문서 참여 발자취를 위해서 Pull Request나 직접 Push를 (권한이 있다면!!) 하는건 어떨까요? :-)

**Comment by tael** [comment]
아 이거 처음에 한명이 관리해서 번역하는 단계를 지난건가요?

**Comment by amaranth379** [comment]
초안 번역(정리) 완두님이 다 하셨데요 (후덜덜 벌써..)
분량을 나눠서 중복작업 없이 번역 들어가야 할 것 같아요

**Comment by wan2land** [comment]
일단 이건 닫습니다.
